// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_ArcPushStatePtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcPushStatePtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_FindMyFriendsClientDefaultAnisetteProviderPtr =>
          wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyFriendsClientDefaultAnisetteProviderPtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_FindMyPhoneClientDefaultAnisetteProviderPtr =>
          wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyPhoneClientDefaultAnisetteProviderPtr;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_IdsUserPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIDSUserPtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_JoinedOsConfigPtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinedOSConfigPtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_NsArrayLpIconMetadataPtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPIconMetadataPtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_NsArrayLpImageMetadataPtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPImageMetadataPtr;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_VerifyBodyPtr =>
      wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVerifyBodyPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  ArcPushState
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcPushState(
          dynamic raw);

  @protected
  FindMyFriendsClientDefaultAnisetteProvider
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyFriendsClientDefaultAnisetteProvider(
          dynamic raw);

  @protected
  FindMyPhoneClientDefaultAnisetteProvider
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyPhoneClientDefaultAnisetteProvider(
          dynamic raw);

  @protected
  IdsUser
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIDSUser(
          dynamic raw);

  @protected
  JoinedOsConfig
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinedOSConfig(
          dynamic raw);

  @protected
  NsArrayLpIconMetadata
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPIconMetadata(
          dynamic raw);

  @protected
  NsArrayLpImageMetadata
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPImageMetadata(
          dynamic raw);

  @protected
  VerifyBody
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVerifyBody(
          dynamic raw);

  @protected
  FindMyFriendsClientDefaultAnisetteProvider
      dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyFriendsClientDefaultAnisetteProvider(
          dynamic raw);

  @protected
  FindMyPhoneClientDefaultAnisetteProvider
      dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyPhoneClientDefaultAnisetteProvider(
          dynamic raw);

  @protected
  ArcPushState
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcPushState(
          dynamic raw);

  @protected
  IdsUser
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIDSUser(
          dynamic raw);

  @protected
  JoinedOsConfig
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinedOSConfig(
          dynamic raw);

  @protected
  VerifyBody
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVerifyBody(
          dynamic raw);

  @protected
  int dco_decode_CastedPrimitive_u_64(dynamic raw);

  @protected
  int dco_decode_CastedPrimitive_usize(dynamic raw);

  @protected
  Map<String, bool> dco_decode_Map_String_bool(dynamic raw);

  @protected
  ArcPushState
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcPushState(
          dynamic raw);

  @protected
  FindMyFriendsClientDefaultAnisetteProvider
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyFriendsClientDefaultAnisetteProvider(
          dynamic raw);

  @protected
  FindMyPhoneClientDefaultAnisetteProvider
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyPhoneClientDefaultAnisetteProvider(
          dynamic raw);

  @protected
  IdsUser
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIDSUser(
          dynamic raw);

  @protected
  JoinedOsConfig
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinedOSConfig(
          dynamic raw);

  @protected
  NsArrayLpIconMetadata
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPIconMetadata(
          dynamic raw);

  @protected
  NsArrayLpImageMetadata
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPImageMetadata(
          dynamic raw);

  @protected
  VerifyBody
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVerifyBody(
          dynamic raw);

  @protected
  RustStreamSink<MMCSTransferProgress>
      dco_decode_StreamSink_mmcs_transfer_progress_Sse(dynamic raw);

  @protected
  RustStreamSink<TransferProgress> dco_decode_StreamSink_transfer_progress_Sse(
      dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  Address dco_decode_address(dynamic raw);

  @protected
  Attachment dco_decode_attachment(dynamic raw);

  @protected
  AttachmentType dco_decode_attachment_type(dynamic raw);

  @protected
  Balloon dco_decode_balloon(dynamic raw);

  @protected
  BalloonLayout dco_decode_balloon_layout(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  IdsUser
      dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIDSUser(
          dynamic raw);

  @protected
  JoinedOsConfig
      dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinedOSConfig(
          dynamic raw);

  @protected
  NsArrayLpIconMetadata
      dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPIconMetadata(
          dynamic raw);

  @protected
  NsArrayLpImageMetadata
      dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPImageMetadata(
          dynamic raw);

  @protected
  Address dco_decode_box_autoadd_address(dynamic raw);

  @protected
  Attachment dco_decode_box_autoadd_attachment(dynamic raw);

  @protected
  Balloon dco_decode_box_autoadd_balloon(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  ChangeParticipantMessage dco_decode_box_autoadd_change_participant_message(
      dynamic raw);

  @protected
  ConversationData dco_decode_box_autoadd_conversation_data(dynamic raw);

  @protected
  EditMessage dco_decode_box_autoadd_edit_message(dynamic raw);

  @protected
  ErrorMessage dco_decode_box_autoadd_error_message(dynamic raw);

  @protected
  ExtensionApp dco_decode_box_autoadd_extension_app(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  HwExtra dco_decode_box_autoadd_hw_extra(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  IconChangeMessage dco_decode_box_autoadd_icon_change_message(dynamic raw);

  @protected
  LinkMeta dco_decode_box_autoadd_link_meta(dynamic raw);

  @protected
  Location dco_decode_box_autoadd_location(dynamic raw);

  @protected
  LoginState dco_decode_box_autoadd_login_state(dynamic raw);

  @protected
  LPIconMetadata dco_decode_box_autoadd_lp_icon_metadata(dynamic raw);

  @protected
  LPImageMetadata dco_decode_box_autoadd_lp_image_metadata(dynamic raw);

  @protected
  Message dco_decode_box_autoadd_message(dynamic raw);

  @protected
  MessageInst dco_decode_box_autoadd_message_inst(dynamic raw);

  @protected
  MessageParts dco_decode_box_autoadd_message_parts(dynamic raw);

  @protected
  MMCSFile dco_decode_box_autoadd_mmcs_file(dynamic raw);

  @protected
  MoveToRecycleBinMessage dco_decode_box_autoadd_move_to_recycle_bin_message(
      dynamic raw);

  @protected
  NormalMessage dco_decode_box_autoadd_normal_message(dynamic raw);

  @protected
  NSURL dco_decode_box_autoadd_nsurl(dynamic raw);

  @protected
  OperatedChat dco_decode_box_autoadd_operated_chat(dynamic raw);

  @protected
  PartExtension dco_decode_box_autoadd_part_extension(dynamic raw);

  @protected
  PermanentDeleteMessage dco_decode_box_autoadd_permanent_delete_message(
      dynamic raw);

  @protected
  PushMessage dco_decode_box_autoadd_push_message(dynamic raw);

  @protected
  ReactMessage dco_decode_box_autoadd_react_message(dynamic raw);

  @protected
  Reaction dco_decode_box_autoadd_reaction(dynamic raw);

  @protected
  RegisterState dco_decode_box_autoadd_register_state(dynamic raw);

  @protected
  RenameMessage dco_decode_box_autoadd_rename_message(dynamic raw);

  @protected
  RichLinkImageAttachmentSubstitute
      dco_decode_box_autoadd_rich_link_image_attachment_substitute(dynamic raw);

  @protected
  SupportAction dco_decode_box_autoadd_support_action(dynamic raw);

  @protected
  SupportAlert dco_decode_box_autoadd_support_alert(dynamic raw);

  @protected
  TextFlags dco_decode_box_autoadd_text_flags(dynamic raw);

  @protected
  TextFormat dco_decode_box_autoadd_text_format(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  UnsendMessage dco_decode_box_autoadd_unsend_message(dynamic raw);

  @protected
  UpdateExtensionMessage dco_decode_box_autoadd_update_extension_message(
      dynamic raw);

  @protected
  ChangeParticipantMessage dco_decode_change_participant_message(dynamic raw);

  @protected
  ConversationData dco_decode_conversation_data(dynamic raw);

  @protected
  DeleteTarget dco_decode_delete_target(dynamic raw);

  @protected
  DeviceInfo dco_decode_device_info(dynamic raw);

  @protected
  EditMessage dco_decode_edit_message(dynamic raw);

  @protected
  ErrorMessage dco_decode_error_message(dynamic raw);

  @protected
  ExtensionApp dco_decode_extension_app(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  Follow dco_decode_follow(dynamic raw);

  @protected
  FoundDevice dco_decode_found_device(dynamic raw);

  @protected
  HwExtra dco_decode_hw_extra(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  IconChangeMessage dco_decode_icon_change_message(dynamic raw);

  @protected
  IndexedMessagePart dco_decode_indexed_message_part(dynamic raw);

  @protected
  LinkMeta dco_decode_link_meta(dynamic raw);

  @protected
  List<IdsUser>
      dco_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIDSUser(
          dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Follow> dco_decode_list_follow(dynamic raw);

  @protected
  List<FoundDevice> dco_decode_list_found_device(dynamic raw);

  @protected
  List<IndexedMessagePart> dco_decode_list_indexed_message_part(dynamic raw);

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw);

  @protected
  List<MessageTarget> dco_decode_list_message_target(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<PrivateDeviceInfo> dco_decode_list_private_device_info(dynamic raw);

  @protected
  List<(String, bool)> dco_decode_list_record_string_bool(dynamic raw);

  @protected
  List<TrustedPhoneNumber> dco_decode_list_trusted_phone_number(dynamic raw);

  @protected
  Location dco_decode_location(dynamic raw);

  @protected
  LoginState dco_decode_login_state(dynamic raw);

  @protected
  LPIconMetadata dco_decode_lp_icon_metadata(dynamic raw);

  @protected
  LPImageMetadata dco_decode_lp_image_metadata(dynamic raw);

  @protected
  LPLinkMetadata dco_decode_lp_link_metadata(dynamic raw);

  @protected
  Message dco_decode_message(dynamic raw);

  @protected
  MessageInst dco_decode_message_inst(dynamic raw);

  @protected
  MessagePart dco_decode_message_part(dynamic raw);

  @protected
  MessageParts dco_decode_message_parts(dynamic raw);

  @protected
  MessageTarget dco_decode_message_target(dynamic raw);

  @protected
  MessageType dco_decode_message_type(dynamic raw);

  @protected
  MMCSFile dco_decode_mmcs_file(dynamic raw);

  @protected
  MMCSTransferProgress dco_decode_mmcs_transfer_progress(dynamic raw);

  @protected
  MoveToRecycleBinMessage dco_decode_move_to_recycle_bin_message(dynamic raw);

  @protected
  MyAsyncRuntime dco_decode_my_async_runtime(dynamic raw);

  @protected
  NormalMessage dco_decode_normal_message(dynamic raw);

  @protected
  NSDictionaryClass dco_decode_ns_dictionary_class(dynamic raw);

  @protected
  NSURL dco_decode_nsurl(dynamic raw);

  @protected
  OperatedChat dco_decode_operated_chat(dynamic raw);

  @protected
  int? dco_decode_opt_CastedPrimitive_u_64(dynamic raw);

  @protected
  int? dco_decode_opt_CastedPrimitive_usize(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  IdsUser?
      dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIDSUser(
          dynamic raw);

  @protected
  JoinedOsConfig?
      dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinedOSConfig(
          dynamic raw);

  @protected
  NsArrayLpIconMetadata?
      dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPIconMetadata(
          dynamic raw);

  @protected
  NsArrayLpImageMetadata?
      dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPImageMetadata(
          dynamic raw);

  @protected
  Address? dco_decode_opt_box_autoadd_address(dynamic raw);

  @protected
  Attachment? dco_decode_opt_box_autoadd_attachment(dynamic raw);

  @protected
  Balloon? dco_decode_opt_box_autoadd_balloon(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  ConversationData? dco_decode_opt_box_autoadd_conversation_data(dynamic raw);

  @protected
  ExtensionApp? dco_decode_opt_box_autoadd_extension_app(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  LinkMeta? dco_decode_opt_box_autoadd_link_meta(dynamic raw);

  @protected
  Location? dco_decode_opt_box_autoadd_location(dynamic raw);

  @protected
  LoginState? dco_decode_opt_box_autoadd_login_state(dynamic raw);

  @protected
  LPIconMetadata? dco_decode_opt_box_autoadd_lp_icon_metadata(dynamic raw);

  @protected
  LPImageMetadata? dco_decode_opt_box_autoadd_lp_image_metadata(dynamic raw);

  @protected
  MMCSFile? dco_decode_opt_box_autoadd_mmcs_file(dynamic raw);

  @protected
  NSURL? dco_decode_opt_box_autoadd_nsurl(dynamic raw);

  @protected
  PartExtension? dco_decode_opt_box_autoadd_part_extension(dynamic raw);

  @protected
  PushMessage? dco_decode_opt_box_autoadd_push_message(dynamic raw);

  @protected
  RichLinkImageAttachmentSubstitute?
      dco_decode_opt_box_autoadd_rich_link_image_attachment_substitute(
          dynamic raw);

  @protected
  SupportAction? dco_decode_opt_box_autoadd_support_action(dynamic raw);

  @protected
  SupportAlert? dco_decode_opt_box_autoadd_support_alert(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  List<MessageTarget>? dco_decode_opt_list_message_target(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  PartExtension dco_decode_part_extension(dynamic raw);

  @protected
  PermanentDeleteMessage dco_decode_permanent_delete_message(dynamic raw);

  @protected
  PollResult dco_decode_poll_result(dynamic raw);

  @protected
  PrivateDeviceInfo dco_decode_private_device_info(dynamic raw);

  @protected
  PushMessage dco_decode_push_message(dynamic raw);

  @protected
  ReactMessage dco_decode_react_message(dynamic raw);

  @protected
  ReactMessageType dco_decode_react_message_type(dynamic raw);

  @protected
  Reaction dco_decode_reaction(dynamic raw);

  @protected
  (List<TrustedPhoneNumber>, LoginState?)
      dco_decode_record_list_trusted_phone_number_opt_box_autoadd_login_state(
          dynamic raw);

  @protected
  (
    LoginState,
    IdsUser?
  ) dco_decode_record_login_state_opt_box_autoadd_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_ids_user(
      dynamic raw);

  @protected
  (String, bool) dco_decode_record_string_bool(dynamic raw);

  @protected
  RegisterState dco_decode_register_state(dynamic raw);

  @protected
  RegistrationPhase dco_decode_registration_phase(dynamic raw);

  @protected
  RenameMessage dco_decode_rename_message(dynamic raw);

  @protected
  RichLinkImageAttachmentSubstitute
      dco_decode_rich_link_image_attachment_substitute(dynamic raw);

  @protected
  SupportAction dco_decode_support_action(dynamic raw);

  @protected
  SupportAlert dco_decode_support_alert(dynamic raw);

  @protected
  TextEffect dco_decode_text_effect(dynamic raw);

  @protected
  TextFlags dco_decode_text_flags(dynamic raw);

  @protected
  TextFormat dco_decode_text_format(dynamic raw);

  @protected
  TransferProgress dco_decode_transfer_progress(dynamic raw);

  @protected
  TrustedPhoneNumber dco_decode_trusted_phone_number(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UnsendMessage dco_decode_unsend_message(dynamic raw);

  @protected
  UpdateExtensionMessage dco_decode_update_extension_message(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  ArcPushState
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcPushState(
          SseDeserializer deserializer);

  @protected
  FindMyFriendsClientDefaultAnisetteProvider
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyFriendsClientDefaultAnisetteProvider(
          SseDeserializer deserializer);

  @protected
  FindMyPhoneClientDefaultAnisetteProvider
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyPhoneClientDefaultAnisetteProvider(
          SseDeserializer deserializer);

  @protected
  IdsUser
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIDSUser(
          SseDeserializer deserializer);

  @protected
  JoinedOsConfig
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinedOSConfig(
          SseDeserializer deserializer);

  @protected
  NsArrayLpIconMetadata
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPIconMetadata(
          SseDeserializer deserializer);

  @protected
  NsArrayLpImageMetadata
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPImageMetadata(
          SseDeserializer deserializer);

  @protected
  VerifyBody
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVerifyBody(
          SseDeserializer deserializer);

  @protected
  FindMyFriendsClientDefaultAnisetteProvider
      sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyFriendsClientDefaultAnisetteProvider(
          SseDeserializer deserializer);

  @protected
  FindMyPhoneClientDefaultAnisetteProvider
      sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyPhoneClientDefaultAnisetteProvider(
          SseDeserializer deserializer);

  @protected
  ArcPushState
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcPushState(
          SseDeserializer deserializer);

  @protected
  IdsUser
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIDSUser(
          SseDeserializer deserializer);

  @protected
  JoinedOsConfig
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinedOSConfig(
          SseDeserializer deserializer);

  @protected
  VerifyBody
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVerifyBody(
          SseDeserializer deserializer);

  @protected
  int sse_decode_CastedPrimitive_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_CastedPrimitive_usize(SseDeserializer deserializer);

  @protected
  Map<String, bool> sse_decode_Map_String_bool(SseDeserializer deserializer);

  @protected
  ArcPushState
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcPushState(
          SseDeserializer deserializer);

  @protected
  FindMyFriendsClientDefaultAnisetteProvider
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyFriendsClientDefaultAnisetteProvider(
          SseDeserializer deserializer);

  @protected
  FindMyPhoneClientDefaultAnisetteProvider
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyPhoneClientDefaultAnisetteProvider(
          SseDeserializer deserializer);

  @protected
  IdsUser
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIDSUser(
          SseDeserializer deserializer);

  @protected
  JoinedOsConfig
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinedOSConfig(
          SseDeserializer deserializer);

  @protected
  NsArrayLpIconMetadata
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPIconMetadata(
          SseDeserializer deserializer);

  @protected
  NsArrayLpImageMetadata
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPImageMetadata(
          SseDeserializer deserializer);

  @protected
  VerifyBody
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVerifyBody(
          SseDeserializer deserializer);

  @protected
  RustStreamSink<MMCSTransferProgress>
      sse_decode_StreamSink_mmcs_transfer_progress_Sse(
          SseDeserializer deserializer);

  @protected
  RustStreamSink<TransferProgress> sse_decode_StreamSink_transfer_progress_Sse(
      SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  Address sse_decode_address(SseDeserializer deserializer);

  @protected
  Attachment sse_decode_attachment(SseDeserializer deserializer);

  @protected
  AttachmentType sse_decode_attachment_type(SseDeserializer deserializer);

  @protected
  Balloon sse_decode_balloon(SseDeserializer deserializer);

  @protected
  BalloonLayout sse_decode_balloon_layout(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  IdsUser
      sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIDSUser(
          SseDeserializer deserializer);

  @protected
  JoinedOsConfig
      sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinedOSConfig(
          SseDeserializer deserializer);

  @protected
  NsArrayLpIconMetadata
      sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPIconMetadata(
          SseDeserializer deserializer);

  @protected
  NsArrayLpImageMetadata
      sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPImageMetadata(
          SseDeserializer deserializer);

  @protected
  Address sse_decode_box_autoadd_address(SseDeserializer deserializer);

  @protected
  Attachment sse_decode_box_autoadd_attachment(SseDeserializer deserializer);

  @protected
  Balloon sse_decode_box_autoadd_balloon(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  ChangeParticipantMessage sse_decode_box_autoadd_change_participant_message(
      SseDeserializer deserializer);

  @protected
  ConversationData sse_decode_box_autoadd_conversation_data(
      SseDeserializer deserializer);

  @protected
  EditMessage sse_decode_box_autoadd_edit_message(SseDeserializer deserializer);

  @protected
  ErrorMessage sse_decode_box_autoadd_error_message(
      SseDeserializer deserializer);

  @protected
  ExtensionApp sse_decode_box_autoadd_extension_app(
      SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  HwExtra sse_decode_box_autoadd_hw_extra(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  IconChangeMessage sse_decode_box_autoadd_icon_change_message(
      SseDeserializer deserializer);

  @protected
  LinkMeta sse_decode_box_autoadd_link_meta(SseDeserializer deserializer);

  @protected
  Location sse_decode_box_autoadd_location(SseDeserializer deserializer);

  @protected
  LoginState sse_decode_box_autoadd_login_state(SseDeserializer deserializer);

  @protected
  LPIconMetadata sse_decode_box_autoadd_lp_icon_metadata(
      SseDeserializer deserializer);

  @protected
  LPImageMetadata sse_decode_box_autoadd_lp_image_metadata(
      SseDeserializer deserializer);

  @protected
  Message sse_decode_box_autoadd_message(SseDeserializer deserializer);

  @protected
  MessageInst sse_decode_box_autoadd_message_inst(SseDeserializer deserializer);

  @protected
  MessageParts sse_decode_box_autoadd_message_parts(
      SseDeserializer deserializer);

  @protected
  MMCSFile sse_decode_box_autoadd_mmcs_file(SseDeserializer deserializer);

  @protected
  MoveToRecycleBinMessage sse_decode_box_autoadd_move_to_recycle_bin_message(
      SseDeserializer deserializer);

  @protected
  NormalMessage sse_decode_box_autoadd_normal_message(
      SseDeserializer deserializer);

  @protected
  NSURL sse_decode_box_autoadd_nsurl(SseDeserializer deserializer);

  @protected
  OperatedChat sse_decode_box_autoadd_operated_chat(
      SseDeserializer deserializer);

  @protected
  PartExtension sse_decode_box_autoadd_part_extension(
      SseDeserializer deserializer);

  @protected
  PermanentDeleteMessage sse_decode_box_autoadd_permanent_delete_message(
      SseDeserializer deserializer);

  @protected
  PushMessage sse_decode_box_autoadd_push_message(SseDeserializer deserializer);

  @protected
  ReactMessage sse_decode_box_autoadd_react_message(
      SseDeserializer deserializer);

  @protected
  Reaction sse_decode_box_autoadd_reaction(SseDeserializer deserializer);

  @protected
  RegisterState sse_decode_box_autoadd_register_state(
      SseDeserializer deserializer);

  @protected
  RenameMessage sse_decode_box_autoadd_rename_message(
      SseDeserializer deserializer);

  @protected
  RichLinkImageAttachmentSubstitute
      sse_decode_box_autoadd_rich_link_image_attachment_substitute(
          SseDeserializer deserializer);

  @protected
  SupportAction sse_decode_box_autoadd_support_action(
      SseDeserializer deserializer);

  @protected
  SupportAlert sse_decode_box_autoadd_support_alert(
      SseDeserializer deserializer);

  @protected
  TextFlags sse_decode_box_autoadd_text_flags(SseDeserializer deserializer);

  @protected
  TextFormat sse_decode_box_autoadd_text_format(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  UnsendMessage sse_decode_box_autoadd_unsend_message(
      SseDeserializer deserializer);

  @protected
  UpdateExtensionMessage sse_decode_box_autoadd_update_extension_message(
      SseDeserializer deserializer);

  @protected
  ChangeParticipantMessage sse_decode_change_participant_message(
      SseDeserializer deserializer);

  @protected
  ConversationData sse_decode_conversation_data(SseDeserializer deserializer);

  @protected
  DeleteTarget sse_decode_delete_target(SseDeserializer deserializer);

  @protected
  DeviceInfo sse_decode_device_info(SseDeserializer deserializer);

  @protected
  EditMessage sse_decode_edit_message(SseDeserializer deserializer);

  @protected
  ErrorMessage sse_decode_error_message(SseDeserializer deserializer);

  @protected
  ExtensionApp sse_decode_extension_app(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  Follow sse_decode_follow(SseDeserializer deserializer);

  @protected
  FoundDevice sse_decode_found_device(SseDeserializer deserializer);

  @protected
  HwExtra sse_decode_hw_extra(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  IconChangeMessage sse_decode_icon_change_message(
      SseDeserializer deserializer);

  @protected
  IndexedMessagePart sse_decode_indexed_message_part(
      SseDeserializer deserializer);

  @protected
  LinkMeta sse_decode_link_meta(SseDeserializer deserializer);

  @protected
  List<IdsUser>
      sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIDSUser(
          SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Follow> sse_decode_list_follow(SseDeserializer deserializer);

  @protected
  List<FoundDevice> sse_decode_list_found_device(SseDeserializer deserializer);

  @protected
  List<IndexedMessagePart> sse_decode_list_indexed_message_part(
      SseDeserializer deserializer);

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
      SseDeserializer deserializer);

  @protected
  List<MessageTarget> sse_decode_list_message_target(
      SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<PrivateDeviceInfo> sse_decode_list_private_device_info(
      SseDeserializer deserializer);

  @protected
  List<(String, bool)> sse_decode_list_record_string_bool(
      SseDeserializer deserializer);

  @protected
  List<TrustedPhoneNumber> sse_decode_list_trusted_phone_number(
      SseDeserializer deserializer);

  @protected
  Location sse_decode_location(SseDeserializer deserializer);

  @protected
  LoginState sse_decode_login_state(SseDeserializer deserializer);

  @protected
  LPIconMetadata sse_decode_lp_icon_metadata(SseDeserializer deserializer);

  @protected
  LPImageMetadata sse_decode_lp_image_metadata(SseDeserializer deserializer);

  @protected
  LPLinkMetadata sse_decode_lp_link_metadata(SseDeserializer deserializer);

  @protected
  Message sse_decode_message(SseDeserializer deserializer);

  @protected
  MessageInst sse_decode_message_inst(SseDeserializer deserializer);

  @protected
  MessagePart sse_decode_message_part(SseDeserializer deserializer);

  @protected
  MessageParts sse_decode_message_parts(SseDeserializer deserializer);

  @protected
  MessageTarget sse_decode_message_target(SseDeserializer deserializer);

  @protected
  MessageType sse_decode_message_type(SseDeserializer deserializer);

  @protected
  MMCSFile sse_decode_mmcs_file(SseDeserializer deserializer);

  @protected
  MMCSTransferProgress sse_decode_mmcs_transfer_progress(
      SseDeserializer deserializer);

  @protected
  MoveToRecycleBinMessage sse_decode_move_to_recycle_bin_message(
      SseDeserializer deserializer);

  @protected
  MyAsyncRuntime sse_decode_my_async_runtime(SseDeserializer deserializer);

  @protected
  NormalMessage sse_decode_normal_message(SseDeserializer deserializer);

  @protected
  NSDictionaryClass sse_decode_ns_dictionary_class(
      SseDeserializer deserializer);

  @protected
  NSURL sse_decode_nsurl(SseDeserializer deserializer);

  @protected
  OperatedChat sse_decode_operated_chat(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_CastedPrimitive_u_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_CastedPrimitive_usize(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  IdsUser?
      sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIDSUser(
          SseDeserializer deserializer);

  @protected
  JoinedOsConfig?
      sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinedOSConfig(
          SseDeserializer deserializer);

  @protected
  NsArrayLpIconMetadata?
      sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPIconMetadata(
          SseDeserializer deserializer);

  @protected
  NsArrayLpImageMetadata?
      sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPImageMetadata(
          SseDeserializer deserializer);

  @protected
  Address? sse_decode_opt_box_autoadd_address(SseDeserializer deserializer);

  @protected
  Attachment? sse_decode_opt_box_autoadd_attachment(
      SseDeserializer deserializer);

  @protected
  Balloon? sse_decode_opt_box_autoadd_balloon(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  ConversationData? sse_decode_opt_box_autoadd_conversation_data(
      SseDeserializer deserializer);

  @protected
  ExtensionApp? sse_decode_opt_box_autoadd_extension_app(
      SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  LinkMeta? sse_decode_opt_box_autoadd_link_meta(SseDeserializer deserializer);

  @protected
  Location? sse_decode_opt_box_autoadd_location(SseDeserializer deserializer);

  @protected
  LoginState? sse_decode_opt_box_autoadd_login_state(
      SseDeserializer deserializer);

  @protected
  LPIconMetadata? sse_decode_opt_box_autoadd_lp_icon_metadata(
      SseDeserializer deserializer);

  @protected
  LPImageMetadata? sse_decode_opt_box_autoadd_lp_image_metadata(
      SseDeserializer deserializer);

  @protected
  MMCSFile? sse_decode_opt_box_autoadd_mmcs_file(SseDeserializer deserializer);

  @protected
  NSURL? sse_decode_opt_box_autoadd_nsurl(SseDeserializer deserializer);

  @protected
  PartExtension? sse_decode_opt_box_autoadd_part_extension(
      SseDeserializer deserializer);

  @protected
  PushMessage? sse_decode_opt_box_autoadd_push_message(
      SseDeserializer deserializer);

  @protected
  RichLinkImageAttachmentSubstitute?
      sse_decode_opt_box_autoadd_rich_link_image_attachment_substitute(
          SseDeserializer deserializer);

  @protected
  SupportAction? sse_decode_opt_box_autoadd_support_action(
      SseDeserializer deserializer);

  @protected
  SupportAlert? sse_decode_opt_box_autoadd_support_alert(
      SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  List<MessageTarget>? sse_decode_opt_list_message_target(
      SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  PartExtension sse_decode_part_extension(SseDeserializer deserializer);

  @protected
  PermanentDeleteMessage sse_decode_permanent_delete_message(
      SseDeserializer deserializer);

  @protected
  PollResult sse_decode_poll_result(SseDeserializer deserializer);

  @protected
  PrivateDeviceInfo sse_decode_private_device_info(
      SseDeserializer deserializer);

  @protected
  PushMessage sse_decode_push_message(SseDeserializer deserializer);

  @protected
  ReactMessage sse_decode_react_message(SseDeserializer deserializer);

  @protected
  ReactMessageType sse_decode_react_message_type(SseDeserializer deserializer);

  @protected
  Reaction sse_decode_reaction(SseDeserializer deserializer);

  @protected
  (List<TrustedPhoneNumber>, LoginState?)
      sse_decode_record_list_trusted_phone_number_opt_box_autoadd_login_state(
          SseDeserializer deserializer);

  @protected
  (
    LoginState,
    IdsUser?
  ) sse_decode_record_login_state_opt_box_autoadd_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_ids_user(
      SseDeserializer deserializer);

  @protected
  (String, bool) sse_decode_record_string_bool(SseDeserializer deserializer);

  @protected
  RegisterState sse_decode_register_state(SseDeserializer deserializer);

  @protected
  RegistrationPhase sse_decode_registration_phase(SseDeserializer deserializer);

  @protected
  RenameMessage sse_decode_rename_message(SseDeserializer deserializer);

  @protected
  RichLinkImageAttachmentSubstitute
      sse_decode_rich_link_image_attachment_substitute(
          SseDeserializer deserializer);

  @protected
  SupportAction sse_decode_support_action(SseDeserializer deserializer);

  @protected
  SupportAlert sse_decode_support_alert(SseDeserializer deserializer);

  @protected
  TextEffect sse_decode_text_effect(SseDeserializer deserializer);

  @protected
  TextFlags sse_decode_text_flags(SseDeserializer deserializer);

  @protected
  TextFormat sse_decode_text_format(SseDeserializer deserializer);

  @protected
  TransferProgress sse_decode_transfer_progress(SseDeserializer deserializer);

  @protected
  TrustedPhoneNumber sse_decode_trusted_phone_number(
      SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UnsendMessage sse_decode_unsend_message(SseDeserializer deserializer);

  @protected
  UpdateExtensionMessage sse_decode_update_extension_message(
      SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcPushState(
          ArcPushState self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyFriendsClientDefaultAnisetteProvider(
          FindMyFriendsClientDefaultAnisetteProvider self,
          SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyPhoneClientDefaultAnisetteProvider(
          FindMyPhoneClientDefaultAnisetteProvider self,
          SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIDSUser(
          IdsUser self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinedOSConfig(
          JoinedOsConfig self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPIconMetadata(
          NsArrayLpIconMetadata self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPImageMetadata(
          NsArrayLpImageMetadata self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVerifyBody(
          VerifyBody self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyFriendsClientDefaultAnisetteProvider(
          FindMyFriendsClientDefaultAnisetteProvider self,
          SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyPhoneClientDefaultAnisetteProvider(
          FindMyPhoneClientDefaultAnisetteProvider self,
          SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcPushState(
          ArcPushState self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIDSUser(
          IdsUser self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinedOSConfig(
          JoinedOsConfig self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVerifyBody(
          VerifyBody self, SseSerializer serializer);

  @protected
  void sse_encode_CastedPrimitive_u_64(int self, SseSerializer serializer);

  @protected
  void sse_encode_CastedPrimitive_usize(int self, SseSerializer serializer);

  @protected
  void sse_encode_Map_String_bool(
      Map<String, bool> self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcPushState(
          ArcPushState self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyFriendsClientDefaultAnisetteProvider(
          FindMyFriendsClientDefaultAnisetteProvider self,
          SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyPhoneClientDefaultAnisetteProvider(
          FindMyPhoneClientDefaultAnisetteProvider self,
          SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIDSUser(
          IdsUser self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinedOSConfig(
          JoinedOsConfig self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPIconMetadata(
          NsArrayLpIconMetadata self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPImageMetadata(
          NsArrayLpImageMetadata self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVerifyBody(
          VerifyBody self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_mmcs_transfer_progress_Sse(
      RustStreamSink<MMCSTransferProgress> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_transfer_progress_Sse(
      RustStreamSink<TransferProgress> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_address(Address self, SseSerializer serializer);

  @protected
  void sse_encode_attachment(Attachment self, SseSerializer serializer);

  @protected
  void sse_encode_attachment_type(
      AttachmentType self, SseSerializer serializer);

  @protected
  void sse_encode_balloon(Balloon self, SseSerializer serializer);

  @protected
  void sse_encode_balloon_layout(BalloonLayout self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void
      sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIDSUser(
          IdsUser self, SseSerializer serializer);

  @protected
  void
      sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinedOSConfig(
          JoinedOsConfig self, SseSerializer serializer);

  @protected
  void
      sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPIconMetadata(
          NsArrayLpIconMetadata self, SseSerializer serializer);

  @protected
  void
      sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPImageMetadata(
          NsArrayLpImageMetadata self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_address(Address self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_attachment(
      Attachment self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_balloon(Balloon self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_change_participant_message(
      ChangeParticipantMessage self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_conversation_data(
      ConversationData self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_edit_message(
      EditMessage self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_error_message(
      ErrorMessage self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_extension_app(
      ExtensionApp self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_hw_extra(HwExtra self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_icon_change_message(
      IconChangeMessage self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_link_meta(
      LinkMeta self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_location(Location self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_login_state(
      LoginState self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_lp_icon_metadata(
      LPIconMetadata self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_lp_image_metadata(
      LPImageMetadata self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_message(Message self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_message_inst(
      MessageInst self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_message_parts(
      MessageParts self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_mmcs_file(
      MMCSFile self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_move_to_recycle_bin_message(
      MoveToRecycleBinMessage self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_normal_message(
      NormalMessage self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_nsurl(NSURL self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_operated_chat(
      OperatedChat self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_part_extension(
      PartExtension self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_permanent_delete_message(
      PermanentDeleteMessage self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_push_message(
      PushMessage self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_react_message(
      ReactMessage self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_reaction(Reaction self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_register_state(
      RegisterState self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_rename_message(
      RenameMessage self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_rich_link_image_attachment_substitute(
      RichLinkImageAttachmentSubstitute self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_support_action(
      SupportAction self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_support_alert(
      SupportAlert self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_text_flags(
      TextFlags self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_text_format(
      TextFormat self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_unsend_message(
      UnsendMessage self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_update_extension_message(
      UpdateExtensionMessage self, SseSerializer serializer);

  @protected
  void sse_encode_change_participant_message(
      ChangeParticipantMessage self, SseSerializer serializer);

  @protected
  void sse_encode_conversation_data(
      ConversationData self, SseSerializer serializer);

  @protected
  void sse_encode_delete_target(DeleteTarget self, SseSerializer serializer);

  @protected
  void sse_encode_device_info(DeviceInfo self, SseSerializer serializer);

  @protected
  void sse_encode_edit_message(EditMessage self, SseSerializer serializer);

  @protected
  void sse_encode_error_message(ErrorMessage self, SseSerializer serializer);

  @protected
  void sse_encode_extension_app(ExtensionApp self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_follow(Follow self, SseSerializer serializer);

  @protected
  void sse_encode_found_device(FoundDevice self, SseSerializer serializer);

  @protected
  void sse_encode_hw_extra(HwExtra self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_icon_change_message(
      IconChangeMessage self, SseSerializer serializer);

  @protected
  void sse_encode_indexed_message_part(
      IndexedMessagePart self, SseSerializer serializer);

  @protected
  void sse_encode_link_meta(LinkMeta self, SseSerializer serializer);

  @protected
  void
      sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIDSUser(
          List<IdsUser> self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_follow(List<Follow> self, SseSerializer serializer);

  @protected
  void sse_encode_list_found_device(
      List<FoundDevice> self, SseSerializer serializer);

  @protected
  void sse_encode_list_indexed_message_part(
      List<IndexedMessagePart> self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_prim_u_8_strict(
      List<Uint8List> self, SseSerializer serializer);

  @protected
  void sse_encode_list_message_target(
      List<MessageTarget> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_private_device_info(
      List<PrivateDeviceInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_string_bool(
      List<(String, bool)> self, SseSerializer serializer);

  @protected
  void sse_encode_list_trusted_phone_number(
      List<TrustedPhoneNumber> self, SseSerializer serializer);

  @protected
  void sse_encode_location(Location self, SseSerializer serializer);

  @protected
  void sse_encode_login_state(LoginState self, SseSerializer serializer);

  @protected
  void sse_encode_lp_icon_metadata(
      LPIconMetadata self, SseSerializer serializer);

  @protected
  void sse_encode_lp_image_metadata(
      LPImageMetadata self, SseSerializer serializer);

  @protected
  void sse_encode_lp_link_metadata(
      LPLinkMetadata self, SseSerializer serializer);

  @protected
  void sse_encode_message(Message self, SseSerializer serializer);

  @protected
  void sse_encode_message_inst(MessageInst self, SseSerializer serializer);

  @protected
  void sse_encode_message_part(MessagePart self, SseSerializer serializer);

  @protected
  void sse_encode_message_parts(MessageParts self, SseSerializer serializer);

  @protected
  void sse_encode_message_target(MessageTarget self, SseSerializer serializer);

  @protected
  void sse_encode_message_type(MessageType self, SseSerializer serializer);

  @protected
  void sse_encode_mmcs_file(MMCSFile self, SseSerializer serializer);

  @protected
  void sse_encode_mmcs_transfer_progress(
      MMCSTransferProgress self, SseSerializer serializer);

  @protected
  void sse_encode_move_to_recycle_bin_message(
      MoveToRecycleBinMessage self, SseSerializer serializer);

  @protected
  void sse_encode_my_async_runtime(
      MyAsyncRuntime self, SseSerializer serializer);

  @protected
  void sse_encode_normal_message(NormalMessage self, SseSerializer serializer);

  @protected
  void sse_encode_ns_dictionary_class(
      NSDictionaryClass self, SseSerializer serializer);

  @protected
  void sse_encode_nsurl(NSURL self, SseSerializer serializer);

  @protected
  void sse_encode_operated_chat(OperatedChat self, SseSerializer serializer);

  @protected
  void sse_encode_opt_CastedPrimitive_u_64(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_CastedPrimitive_usize(
      int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void
      sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIDSUser(
          IdsUser? self, SseSerializer serializer);

  @protected
  void
      sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinedOSConfig(
          JoinedOsConfig? self, SseSerializer serializer);

  @protected
  void
      sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPIconMetadata(
          NsArrayLpIconMetadata? self, SseSerializer serializer);

  @protected
  void
      sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPImageMetadata(
          NsArrayLpImageMetadata? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_address(
      Address? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_attachment(
      Attachment? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_balloon(
      Balloon? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_conversation_data(
      ConversationData? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_extension_app(
      ExtensionApp? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_link_meta(
      LinkMeta? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_location(
      Location? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_login_state(
      LoginState? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_lp_icon_metadata(
      LPIconMetadata? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_lp_image_metadata(
      LPImageMetadata? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_mmcs_file(
      MMCSFile? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_nsurl(NSURL? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_part_extension(
      PartExtension? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_push_message(
      PushMessage? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_rich_link_image_attachment_substitute(
      RichLinkImageAttachmentSubstitute? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_support_action(
      SupportAction? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_support_alert(
      SupportAlert? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_message_target(
      List<MessageTarget>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
      Uint8List? self, SseSerializer serializer);

  @protected
  void sse_encode_part_extension(PartExtension self, SseSerializer serializer);

  @protected
  void sse_encode_permanent_delete_message(
      PermanentDeleteMessage self, SseSerializer serializer);

  @protected
  void sse_encode_poll_result(PollResult self, SseSerializer serializer);

  @protected
  void sse_encode_private_device_info(
      PrivateDeviceInfo self, SseSerializer serializer);

  @protected
  void sse_encode_push_message(PushMessage self, SseSerializer serializer);

  @protected
  void sse_encode_react_message(ReactMessage self, SseSerializer serializer);

  @protected
  void sse_encode_react_message_type(
      ReactMessageType self, SseSerializer serializer);

  @protected
  void sse_encode_reaction(Reaction self, SseSerializer serializer);

  @protected
  void sse_encode_record_list_trusted_phone_number_opt_box_autoadd_login_state(
      (List<TrustedPhoneNumber>, LoginState?) self, SseSerializer serializer);

  @protected
  void
      sse_encode_record_login_state_opt_box_autoadd_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_ids_user(
          (LoginState, IdsUser?) self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_bool(
      (String, bool) self, SseSerializer serializer);

  @protected
  void sse_encode_register_state(RegisterState self, SseSerializer serializer);

  @protected
  void sse_encode_registration_phase(
      RegistrationPhase self, SseSerializer serializer);

  @protected
  void sse_encode_rename_message(RenameMessage self, SseSerializer serializer);

  @protected
  void sse_encode_rich_link_image_attachment_substitute(
      RichLinkImageAttachmentSubstitute self, SseSerializer serializer);

  @protected
  void sse_encode_support_action(SupportAction self, SseSerializer serializer);

  @protected
  void sse_encode_support_alert(SupportAlert self, SseSerializer serializer);

  @protected
  void sse_encode_text_effect(TextEffect self, SseSerializer serializer);

  @protected
  void sse_encode_text_flags(TextFlags self, SseSerializer serializer);

  @protected
  void sse_encode_text_format(TextFormat self, SseSerializer serializer);

  @protected
  void sse_encode_transfer_progress(
      TransferProgress self, SseSerializer serializer);

  @protected
  void sse_encode_trusted_phone_number(
      TrustedPhoneNumber self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_unsend_message(UnsendMessage self, SseSerializer serializer);

  @protected
  void sse_encode_update_extension_message(
      UpdateExtensionMessage self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcPushState(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcPushState(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcPushStatePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_bluebubbles_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcPushState');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcPushState =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcPushStatePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcPushState(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcPushState(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcPushStatePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_bluebubbles_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcPushState');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcPushState =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcPushStatePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyFriendsClientDefaultAnisetteProvider(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyFriendsClientDefaultAnisetteProvider(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyFriendsClientDefaultAnisetteProviderPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_bluebubbles_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyFriendsClientDefaultAnisetteProvider');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyFriendsClientDefaultAnisetteProvider =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyFriendsClientDefaultAnisetteProviderPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyFriendsClientDefaultAnisetteProvider(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyFriendsClientDefaultAnisetteProvider(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyFriendsClientDefaultAnisetteProviderPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_bluebubbles_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyFriendsClientDefaultAnisetteProvider');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyFriendsClientDefaultAnisetteProvider =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyFriendsClientDefaultAnisetteProviderPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyPhoneClientDefaultAnisetteProvider(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyPhoneClientDefaultAnisetteProvider(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyPhoneClientDefaultAnisetteProviderPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_bluebubbles_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyPhoneClientDefaultAnisetteProvider');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyPhoneClientDefaultAnisetteProvider =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyPhoneClientDefaultAnisetteProviderPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyPhoneClientDefaultAnisetteProvider(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyPhoneClientDefaultAnisetteProvider(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyPhoneClientDefaultAnisetteProviderPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_bluebubbles_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyPhoneClientDefaultAnisetteProvider');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyPhoneClientDefaultAnisetteProvider =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFindMyPhoneClientDefaultAnisetteProviderPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIDSUser(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIDSUser(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIDSUserPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_bluebubbles_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIDSUser');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIDSUser =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIDSUserPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIDSUser(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIDSUser(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIDSUserPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_bluebubbles_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIDSUser');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIDSUser =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIDSUserPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinedOSConfig(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinedOSConfig(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinedOSConfigPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_bluebubbles_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinedOSConfig');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinedOSConfig =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinedOSConfigPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinedOSConfig(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinedOSConfig(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinedOSConfigPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_bluebubbles_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinedOSConfig');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinedOSConfig =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoinedOSConfigPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPIconMetadata(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPIconMetadata(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPIconMetadataPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_bluebubbles_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPIconMetadata');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPIconMetadata =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPIconMetadataPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPIconMetadata(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPIconMetadata(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPIconMetadataPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_bluebubbles_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPIconMetadata');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPIconMetadata =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPIconMetadataPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPImageMetadata(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPImageMetadata(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPImageMetadataPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_bluebubbles_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPImageMetadata');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPImageMetadata =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPImageMetadataPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPImageMetadata(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPImageMetadata(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPImageMetadataPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_bluebubbles_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPImageMetadata');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPImageMetadata =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNSArrayLPImageMetadataPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVerifyBody(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVerifyBody(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVerifyBodyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_bluebubbles_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVerifyBody');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVerifyBody =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVerifyBodyPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVerifyBody(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVerifyBody(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVerifyBodyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_bluebubbles_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVerifyBody');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVerifyBody =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVerifyBodyPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
