// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.33.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_ArcPushStatePtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcPushState;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_MacOsConfigPtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMacOSConfig;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ValuePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_VerifyBodyPtr =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVerifyBody;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  ArcPushState
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcPushState(
          dynamic raw);

  @protected
  MacOsConfig
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMacOSConfig(
          dynamic raw);

  @protected
  Value
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          dynamic raw);

  @protected
  VerifyBody
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVerifyBody(
          dynamic raw);

  @protected
  ArcPushState
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcPushState(
          dynamic raw);

  @protected
  MacOsConfig
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMacOSConfig(
          dynamic raw);

  @protected
  VerifyBody
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVerifyBody(
          dynamic raw);

  @protected
  ArcPushState
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcPushState(
          dynamic raw);

  @protected
  MacOsConfig
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMacOSConfig(
          dynamic raw);

  @protected
  Value
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          dynamic raw);

  @protected
  VerifyBody
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVerifyBody(
          dynamic raw);

  @protected
  RustStreamSink<MMCSTransferProgress>
      dco_decode_StreamSink_mmcs_transfer_progress_Sse(dynamic raw);

  @protected
  RustStreamSink<TransferProgress> dco_decode_StreamSink_transfer_progress_Sse(
      dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  DartAttachment dco_decode_box_autoadd_dart_attachment(dynamic raw);

  @protected
  DartChangeParticipantMessage
      dco_decode_box_autoadd_dart_change_participant_message(dynamic raw);

  @protected
  DartConversationData dco_decode_box_autoadd_dart_conversation_data(
      dynamic raw);

  @protected
  DartEditMessage dco_decode_box_autoadd_dart_edit_message(dynamic raw);

  @protected
  DartHwExtra dco_decode_box_autoadd_dart_hw_extra(dynamic raw);

  @protected
  DartIMessage dco_decode_box_autoadd_dart_i_message(dynamic raw);

  @protected
  DartIconChangeMessage dco_decode_box_autoadd_dart_icon_change_message(
      dynamic raw);

  @protected
  DartLoginState dco_decode_box_autoadd_dart_login_state(dynamic raw);

  @protected
  DartMessage dco_decode_box_autoadd_dart_message(dynamic raw);

  @protected
  DartMessageParts dco_decode_box_autoadd_dart_message_parts(dynamic raw);

  @protected
  DartMMCSFile dco_decode_box_autoadd_dart_mmcs_file(dynamic raw);

  @protected
  DartNormalMessage dco_decode_box_autoadd_dart_normal_message(dynamic raw);

  @protected
  DartPartExtension dco_decode_box_autoadd_dart_part_extension(dynamic raw);

  @protected
  DartReactMessage dco_decode_box_autoadd_dart_react_message(dynamic raw);

  @protected
  DartRenameMessage dco_decode_box_autoadd_dart_rename_message(dynamic raw);

  @protected
  DartSupportAction dco_decode_box_autoadd_dart_support_action(dynamic raw);

  @protected
  DartSupportAlert dco_decode_box_autoadd_dart_support_alert(dynamic raw);

  @protected
  DartUnsendMessage dco_decode_box_autoadd_dart_unsend_message(dynamic raw);

  @protected
  DartUpdateExtensionMessage
      dco_decode_box_autoadd_dart_update_extension_message(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_usize(dynamic raw);

  @protected
  DartAttachment dco_decode_dart_attachment(dynamic raw);

  @protected
  DartAttachmentType dco_decode_dart_attachment_type(dynamic raw);

  @protected
  DartChangeParticipantMessage dco_decode_dart_change_participant_message(
      dynamic raw);

  @protected
  DartConversationData dco_decode_dart_conversation_data(dynamic raw);

  @protected
  DartDeviceInfo dco_decode_dart_device_info(dynamic raw);

  @protected
  DartEditMessage dco_decode_dart_edit_message(dynamic raw);

  @protected
  DartHwExtra dco_decode_dart_hw_extra(dynamic raw);

  @protected
  DartIMessage dco_decode_dart_i_message(dynamic raw);

  @protected
  DartIconChangeMessage dco_decode_dart_icon_change_message(dynamic raw);

  @protected
  DartIndexedMessagePart dco_decode_dart_indexed_message_part(dynamic raw);

  @protected
  DartLoginState dco_decode_dart_login_state(dynamic raw);

  @protected
  DartMessage dco_decode_dart_message(dynamic raw);

  @protected
  DartMessagePart dco_decode_dart_message_part(dynamic raw);

  @protected
  DartMessageParts dco_decode_dart_message_parts(dynamic raw);

  @protected
  DartMessageTarget dco_decode_dart_message_target(dynamic raw);

  @protected
  DartMessageType dco_decode_dart_message_type(dynamic raw);

  @protected
  DartMMCSFile dco_decode_dart_mmcs_file(dynamic raw);

  @protected
  DartNormalMessage dco_decode_dart_normal_message(dynamic raw);

  @protected
  DartPartExtension dco_decode_dart_part_extension(dynamic raw);

  @protected
  DartPrivateDeviceInfo dco_decode_dart_private_device_info(dynamic raw);

  @protected
  DartReactMessage dco_decode_dart_react_message(dynamic raw);

  @protected
  DartReactMessageType dco_decode_dart_react_message_type(dynamic raw);

  @protected
  DartReaction dco_decode_dart_reaction(dynamic raw);

  @protected
  DartRegisterState dco_decode_dart_register_state(dynamic raw);

  @protected
  DartRenameMessage dco_decode_dart_rename_message(dynamic raw);

  @protected
  DartSupportAction dco_decode_dart_support_action(dynamic raw);

  @protected
  DartSupportAlert dco_decode_dart_support_alert(dynamic raw);

  @protected
  DartTrustedPhoneNumber dco_decode_dart_trusted_phone_number(dynamic raw);

  @protected
  DartUnsendMessage dco_decode_dart_unsend_message(dynamic raw);

  @protected
  DartUpdateExtensionMessage dco_decode_dart_update_extension_message(
      dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  int dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<DartIndexedMessagePart> dco_decode_list_dart_indexed_message_part(
      dynamic raw);

  @protected
  List<DartMessageTarget> dco_decode_list_dart_message_target(dynamic raw);

  @protected
  List<DartPrivateDeviceInfo> dco_decode_list_dart_private_device_info(
      dynamic raw);

  @protected
  List<DartTrustedPhoneNumber> dco_decode_list_dart_trusted_phone_number(
      dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MMCSTransferProgress dco_decode_mmcs_transfer_progress(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  DartAttachment? dco_decode_opt_box_autoadd_dart_attachment(dynamic raw);

  @protected
  DartConversationData? dco_decode_opt_box_autoadd_dart_conversation_data(
      dynamic raw);

  @protected
  DartIMessage? dco_decode_opt_box_autoadd_dart_i_message(dynamic raw);

  @protected
  DartLoginState? dco_decode_opt_box_autoadd_dart_login_state(dynamic raw);

  @protected
  DartMMCSFile? dco_decode_opt_box_autoadd_dart_mmcs_file(dynamic raw);

  @protected
  DartPartExtension? dco_decode_opt_box_autoadd_dart_part_extension(
      dynamic raw);

  @protected
  DartSupportAction? dco_decode_opt_box_autoadd_dart_support_action(
      dynamic raw);

  @protected
  DartSupportAlert? dco_decode_opt_box_autoadd_dart_support_alert(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_usize(dynamic raw);

  @protected
  List<DartMessageTarget>? dco_decode_opt_list_dart_message_target(dynamic raw);

  @protected
  PollResult dco_decode_poll_result(dynamic raw);

  @protected
  (
    List<DartTrustedPhoneNumber>,
    DartLoginState?
  ) dco_decode_record_list_dart_trusted_phone_number_opt_box_autoadd_dart_login_state(
      dynamic raw);

  @protected
  RegistrationPhase dco_decode_registration_phase(dynamic raw);

  @protected
  TransferProgress dco_decode_transfer_progress(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  int dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  ArcPushState
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcPushState(
          SseDeserializer deserializer);

  @protected
  MacOsConfig
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMacOSConfig(
          SseDeserializer deserializer);

  @protected
  Value
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          SseDeserializer deserializer);

  @protected
  VerifyBody
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVerifyBody(
          SseDeserializer deserializer);

  @protected
  ArcPushState
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcPushState(
          SseDeserializer deserializer);

  @protected
  MacOsConfig
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMacOSConfig(
          SseDeserializer deserializer);

  @protected
  VerifyBody
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVerifyBody(
          SseDeserializer deserializer);

  @protected
  ArcPushState
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcPushState(
          SseDeserializer deserializer);

  @protected
  MacOsConfig
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMacOSConfig(
          SseDeserializer deserializer);

  @protected
  Value
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          SseDeserializer deserializer);

  @protected
  VerifyBody
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVerifyBody(
          SseDeserializer deserializer);

  @protected
  RustStreamSink<MMCSTransferProgress>
      sse_decode_StreamSink_mmcs_transfer_progress_Sse(
          SseDeserializer deserializer);

  @protected
  RustStreamSink<TransferProgress> sse_decode_StreamSink_transfer_progress_Sse(
      SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  DartAttachment sse_decode_box_autoadd_dart_attachment(
      SseDeserializer deserializer);

  @protected
  DartChangeParticipantMessage
      sse_decode_box_autoadd_dart_change_participant_message(
          SseDeserializer deserializer);

  @protected
  DartConversationData sse_decode_box_autoadd_dart_conversation_data(
      SseDeserializer deserializer);

  @protected
  DartEditMessage sse_decode_box_autoadd_dart_edit_message(
      SseDeserializer deserializer);

  @protected
  DartHwExtra sse_decode_box_autoadd_dart_hw_extra(
      SseDeserializer deserializer);

  @protected
  DartIMessage sse_decode_box_autoadd_dart_i_message(
      SseDeserializer deserializer);

  @protected
  DartIconChangeMessage sse_decode_box_autoadd_dart_icon_change_message(
      SseDeserializer deserializer);

  @protected
  DartLoginState sse_decode_box_autoadd_dart_login_state(
      SseDeserializer deserializer);

  @protected
  DartMessage sse_decode_box_autoadd_dart_message(SseDeserializer deserializer);

  @protected
  DartMessageParts sse_decode_box_autoadd_dart_message_parts(
      SseDeserializer deserializer);

  @protected
  DartMMCSFile sse_decode_box_autoadd_dart_mmcs_file(
      SseDeserializer deserializer);

  @protected
  DartNormalMessage sse_decode_box_autoadd_dart_normal_message(
      SseDeserializer deserializer);

  @protected
  DartPartExtension sse_decode_box_autoadd_dart_part_extension(
      SseDeserializer deserializer);

  @protected
  DartReactMessage sse_decode_box_autoadd_dart_react_message(
      SseDeserializer deserializer);

  @protected
  DartRenameMessage sse_decode_box_autoadd_dart_rename_message(
      SseDeserializer deserializer);

  @protected
  DartSupportAction sse_decode_box_autoadd_dart_support_action(
      SseDeserializer deserializer);

  @protected
  DartSupportAlert sse_decode_box_autoadd_dart_support_alert(
      SseDeserializer deserializer);

  @protected
  DartUnsendMessage sse_decode_box_autoadd_dart_unsend_message(
      SseDeserializer deserializer);

  @protected
  DartUpdateExtensionMessage
      sse_decode_box_autoadd_dart_update_extension_message(
          SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  DartAttachment sse_decode_dart_attachment(SseDeserializer deserializer);

  @protected
  DartAttachmentType sse_decode_dart_attachment_type(
      SseDeserializer deserializer);

  @protected
  DartChangeParticipantMessage sse_decode_dart_change_participant_message(
      SseDeserializer deserializer);

  @protected
  DartConversationData sse_decode_dart_conversation_data(
      SseDeserializer deserializer);

  @protected
  DartDeviceInfo sse_decode_dart_device_info(SseDeserializer deserializer);

  @protected
  DartEditMessage sse_decode_dart_edit_message(SseDeserializer deserializer);

  @protected
  DartHwExtra sse_decode_dart_hw_extra(SseDeserializer deserializer);

  @protected
  DartIMessage sse_decode_dart_i_message(SseDeserializer deserializer);

  @protected
  DartIconChangeMessage sse_decode_dart_icon_change_message(
      SseDeserializer deserializer);

  @protected
  DartIndexedMessagePart sse_decode_dart_indexed_message_part(
      SseDeserializer deserializer);

  @protected
  DartLoginState sse_decode_dart_login_state(SseDeserializer deserializer);

  @protected
  DartMessage sse_decode_dart_message(SseDeserializer deserializer);

  @protected
  DartMessagePart sse_decode_dart_message_part(SseDeserializer deserializer);

  @protected
  DartMessageParts sse_decode_dart_message_parts(SseDeserializer deserializer);

  @protected
  DartMessageTarget sse_decode_dart_message_target(
      SseDeserializer deserializer);

  @protected
  DartMessageType sse_decode_dart_message_type(SseDeserializer deserializer);

  @protected
  DartMMCSFile sse_decode_dart_mmcs_file(SseDeserializer deserializer);

  @protected
  DartNormalMessage sse_decode_dart_normal_message(
      SseDeserializer deserializer);

  @protected
  DartPartExtension sse_decode_dart_part_extension(
      SseDeserializer deserializer);

  @protected
  DartPrivateDeviceInfo sse_decode_dart_private_device_info(
      SseDeserializer deserializer);

  @protected
  DartReactMessage sse_decode_dart_react_message(SseDeserializer deserializer);

  @protected
  DartReactMessageType sse_decode_dart_react_message_type(
      SseDeserializer deserializer);

  @protected
  DartReaction sse_decode_dart_reaction(SseDeserializer deserializer);

  @protected
  DartRegisterState sse_decode_dart_register_state(
      SseDeserializer deserializer);

  @protected
  DartRenameMessage sse_decode_dart_rename_message(
      SseDeserializer deserializer);

  @protected
  DartSupportAction sse_decode_dart_support_action(
      SseDeserializer deserializer);

  @protected
  DartSupportAlert sse_decode_dart_support_alert(SseDeserializer deserializer);

  @protected
  DartTrustedPhoneNumber sse_decode_dart_trusted_phone_number(
      SseDeserializer deserializer);

  @protected
  DartUnsendMessage sse_decode_dart_unsend_message(
      SseDeserializer deserializer);

  @protected
  DartUpdateExtensionMessage sse_decode_dart_update_extension_message(
      SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  int sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<DartIndexedMessagePart> sse_decode_list_dart_indexed_message_part(
      SseDeserializer deserializer);

  @protected
  List<DartMessageTarget> sse_decode_list_dart_message_target(
      SseDeserializer deserializer);

  @protected
  List<DartPrivateDeviceInfo> sse_decode_list_dart_private_device_info(
      SseDeserializer deserializer);

  @protected
  List<DartTrustedPhoneNumber> sse_decode_list_dart_trusted_phone_number(
      SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MMCSTransferProgress sse_decode_mmcs_transfer_progress(
      SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  DartAttachment? sse_decode_opt_box_autoadd_dart_attachment(
      SseDeserializer deserializer);

  @protected
  DartConversationData? sse_decode_opt_box_autoadd_dart_conversation_data(
      SseDeserializer deserializer);

  @protected
  DartIMessage? sse_decode_opt_box_autoadd_dart_i_message(
      SseDeserializer deserializer);

  @protected
  DartLoginState? sse_decode_opt_box_autoadd_dart_login_state(
      SseDeserializer deserializer);

  @protected
  DartMMCSFile? sse_decode_opt_box_autoadd_dart_mmcs_file(
      SseDeserializer deserializer);

  @protected
  DartPartExtension? sse_decode_opt_box_autoadd_dart_part_extension(
      SseDeserializer deserializer);

  @protected
  DartSupportAction? sse_decode_opt_box_autoadd_dart_support_action(
      SseDeserializer deserializer);

  @protected
  DartSupportAlert? sse_decode_opt_box_autoadd_dart_support_alert(
      SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  List<DartMessageTarget>? sse_decode_opt_list_dart_message_target(
      SseDeserializer deserializer);

  @protected
  PollResult sse_decode_poll_result(SseDeserializer deserializer);

  @protected
  (
    List<DartTrustedPhoneNumber>,
    DartLoginState?
  ) sse_decode_record_list_dart_trusted_phone_number_opt_box_autoadd_dart_login_state(
      SseDeserializer deserializer);

  @protected
  RegistrationPhase sse_decode_registration_phase(SseDeserializer deserializer);

  @protected
  TransferProgress sse_decode_transfer_progress(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcPushState(
          ArcPushState self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMacOSConfig(
          MacOsConfig self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          Value self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVerifyBody(
          VerifyBody self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcPushState(
          ArcPushState self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMacOSConfig(
          MacOsConfig self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVerifyBody(
          VerifyBody self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcPushState(
          ArcPushState self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMacOSConfig(
          MacOsConfig self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          Value self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVerifyBody(
          VerifyBody self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_mmcs_transfer_progress_Sse(
      RustStreamSink<MMCSTransferProgress> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_transfer_progress_Sse(
      RustStreamSink<TransferProgress> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_dart_attachment(
      DartAttachment self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_dart_change_participant_message(
      DartChangeParticipantMessage self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_dart_conversation_data(
      DartConversationData self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_dart_edit_message(
      DartEditMessage self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_dart_hw_extra(
      DartHwExtra self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_dart_i_message(
      DartIMessage self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_dart_icon_change_message(
      DartIconChangeMessage self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_dart_login_state(
      DartLoginState self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_dart_message(
      DartMessage self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_dart_message_parts(
      DartMessageParts self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_dart_mmcs_file(
      DartMMCSFile self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_dart_normal_message(
      DartNormalMessage self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_dart_part_extension(
      DartPartExtension self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_dart_react_message(
      DartReactMessage self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_dart_rename_message(
      DartRenameMessage self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_dart_support_action(
      DartSupportAction self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_dart_support_alert(
      DartSupportAlert self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_dart_unsend_message(
      DartUnsendMessage self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_dart_update_extension_message(
      DartUpdateExtensionMessage self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_usize(int self, SseSerializer serializer);

  @protected
  void sse_encode_dart_attachment(
      DartAttachment self, SseSerializer serializer);

  @protected
  void sse_encode_dart_attachment_type(
      DartAttachmentType self, SseSerializer serializer);

  @protected
  void sse_encode_dart_change_participant_message(
      DartChangeParticipantMessage self, SseSerializer serializer);

  @protected
  void sse_encode_dart_conversation_data(
      DartConversationData self, SseSerializer serializer);

  @protected
  void sse_encode_dart_device_info(
      DartDeviceInfo self, SseSerializer serializer);

  @protected
  void sse_encode_dart_edit_message(
      DartEditMessage self, SseSerializer serializer);

  @protected
  void sse_encode_dart_hw_extra(DartHwExtra self, SseSerializer serializer);

  @protected
  void sse_encode_dart_i_message(DartIMessage self, SseSerializer serializer);

  @protected
  void sse_encode_dart_icon_change_message(
      DartIconChangeMessage self, SseSerializer serializer);

  @protected
  void sse_encode_dart_indexed_message_part(
      DartIndexedMessagePart self, SseSerializer serializer);

  @protected
  void sse_encode_dart_login_state(
      DartLoginState self, SseSerializer serializer);

  @protected
  void sse_encode_dart_message(DartMessage self, SseSerializer serializer);

  @protected
  void sse_encode_dart_message_part(
      DartMessagePart self, SseSerializer serializer);

  @protected
  void sse_encode_dart_message_parts(
      DartMessageParts self, SseSerializer serializer);

  @protected
  void sse_encode_dart_message_target(
      DartMessageTarget self, SseSerializer serializer);

  @protected
  void sse_encode_dart_message_type(
      DartMessageType self, SseSerializer serializer);

  @protected
  void sse_encode_dart_mmcs_file(DartMMCSFile self, SseSerializer serializer);

  @protected
  void sse_encode_dart_normal_message(
      DartNormalMessage self, SseSerializer serializer);

  @protected
  void sse_encode_dart_part_extension(
      DartPartExtension self, SseSerializer serializer);

  @protected
  void sse_encode_dart_private_device_info(
      DartPrivateDeviceInfo self, SseSerializer serializer);

  @protected
  void sse_encode_dart_react_message(
      DartReactMessage self, SseSerializer serializer);

  @protected
  void sse_encode_dart_react_message_type(
      DartReactMessageType self, SseSerializer serializer);

  @protected
  void sse_encode_dart_reaction(DartReaction self, SseSerializer serializer);

  @protected
  void sse_encode_dart_register_state(
      DartRegisterState self, SseSerializer serializer);

  @protected
  void sse_encode_dart_rename_message(
      DartRenameMessage self, SseSerializer serializer);

  @protected
  void sse_encode_dart_support_action(
      DartSupportAction self, SseSerializer serializer);

  @protected
  void sse_encode_dart_support_alert(
      DartSupportAlert self, SseSerializer serializer);

  @protected
  void sse_encode_dart_trusted_phone_number(
      DartTrustedPhoneNumber self, SseSerializer serializer);

  @protected
  void sse_encode_dart_unsend_message(
      DartUnsendMessage self, SseSerializer serializer);

  @protected
  void sse_encode_dart_update_extension_message(
      DartUpdateExtensionMessage self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_dart_indexed_message_part(
      List<DartIndexedMessagePart> self, SseSerializer serializer);

  @protected
  void sse_encode_list_dart_message_target(
      List<DartMessageTarget> self, SseSerializer serializer);

  @protected
  void sse_encode_list_dart_private_device_info(
      List<DartPrivateDeviceInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_dart_trusted_phone_number(
      List<DartTrustedPhoneNumber> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_mmcs_transfer_progress(
      MMCSTransferProgress self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_dart_attachment(
      DartAttachment? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_dart_conversation_data(
      DartConversationData? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_dart_i_message(
      DartIMessage? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_dart_login_state(
      DartLoginState? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_dart_mmcs_file(
      DartMMCSFile? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_dart_part_extension(
      DartPartExtension? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_dart_support_action(
      DartSupportAction? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_dart_support_alert(
      DartSupportAlert? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_usize(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_dart_message_target(
      List<DartMessageTarget>? self, SseSerializer serializer);

  @protected
  void sse_encode_poll_result(PollResult self, SseSerializer serializer);

  @protected
  void
      sse_encode_record_list_dart_trusted_phone_number_opt_box_autoadd_dart_login_state(
          (List<DartTrustedPhoneNumber>, DartLoginState?) self,
          SseSerializer serializer);

  @protected
  void sse_encode_registration_phase(
      RegistrationPhase self, SseSerializer serializer);

  @protected
  void sse_encode_transfer_progress(
      TransferProgress self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcPushState(
          dynamic ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcPushState(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcPushState(
          dynamic ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcPushState(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMacOSConfig(
          dynamic ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMacOSConfig(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMacOSConfig(
          dynamic ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMacOSConfig(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          dynamic ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          dynamic ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVerifyBody(
          dynamic ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVerifyBody(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVerifyBody(
          dynamic ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVerifyBody(
              ptr);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
class RustLibWasmModule implements WasmModule {
  @override
  external Object /* Promise */ call([String? moduleName]);

  @override
  external RustLibWasmModule bind(dynamic thisArg, String moduleName);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcPushState(
          dynamic ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcPushState(
          dynamic ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMacOSConfig(
          dynamic ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMacOSConfig(
          dynamic ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          dynamic ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          dynamic ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVerifyBody(
          dynamic ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVerifyBody(
          dynamic ptr);
}
